# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 19:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, help_text='不填写默认为文件名', max_length=255, verbose_name='附件名称')),
                ('文件类型', models.CharField(choices=[('general', '一般文件'), ('contract', '合同'), ('sfz', '身份证'), ('legal_man', '企业法人营业执照'), ('business_license', '营业执照副本')], default='general', max_length=20)),
                ('file', models.FileField(upload_to='upload_path')),
                ('object_id', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
