# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': '附件', 'verbose_name_plural': '附件'},
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='文件类型',
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_type',
            field=models.CharField(choices=[('general', '一般文件'), ('contract', '合同'), ('sfz', '身份证'), ('legal_man', '企业法人营业执照'), ('business_license', '营业执照副本')], default='general', max_length=20, verbose_name='文件类型'),
        ),
    ]
