# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170723_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file_type',
            field=models.CharField(choices=[('general', '一般文件'), ('contract', '合同'), ('sfz', '身份证'), ('legal_man', '企业法人营业执照'), ('bank', '银行开户许可证'), ('credit', '机构信用代码证'), ('business_license', '营业执照副本')], default='general', max_length=20, verbose_name='文件类型'),
        ),
    ]
