# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 17:41
from __future__ import unicode_literals

import core.models.profile
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_accesstoken_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=100, verbose_name='手机')),
                ('avatar', models.ImageField(blank=True, upload_to=core.models.profile.get_upload_to, verbose_name='头像')),
                ('headimgurl', models.CharField(blank=True, max_length=255)),
                ('nickname', models.CharField(blank=True, max_length=200)),
                ('sex', models.SmallIntegerField(choices=[(1, '男性'), (2, '女性')], default=1)),
                ('country', models.CharField(default='中国', max_length=50, verbose_name='国家')),
                ('province', models.CharField(default='', max_length=100, verbose_name='省')),
                ('city', models.CharField(default='', max_length=100, verbose_name='城市')),
                ('prefs', jsonfield.fields.JSONField(blank=True, default={}, verbose_name='偏好设置')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
