# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
