# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-06 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_profile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Site Name', max_length=255)),
                ('site_address', models.BooleanField(default=False)),
                ('custom_css', models.CharField(blank=True, max_length=100)),
                ('allow_custom_css', models.BooleanField(default=False)),
                ('allow_sharefile', models.BooleanField(default=False)),
                ('allow_preview', models.BooleanField(default=False)),
                ('allow_like', models.BooleanField(default=False)),
                ('allow_tag', models.BooleanField(default=False)),
                ('site_log', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/')),
                ('site_favicon', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': '站点设置',
            },
        ),
    ]
