# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-06 09:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0103_auto_20171203_2347'),
        ('core', '0012_siteconf'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=100, verbose_name='手机号码')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='职位')),
                ('company_title', models.CharField(blank=True, max_length=255, verbose_name='公司名称')),
                ('info', models.TextField(blank=True, verbose_name='其它信息')),
                ('reason', models.TextField(blank=True, verbose_name='拒绝理由')),
                ('state', django_fsm.FSMField(default='new', max_length=50)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
