# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-06 09:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_memberapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberapplication',
            name='user',
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='applicant',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditor', to=settings.AUTH_USER_MODEL),
        ),
    ]
