# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-06 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20171206_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberapplication',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
