# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-07 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20171206_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
