# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-07 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20171207_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconf',
            name='wx_redirect_uri',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
