# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-07 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_siteconf_wx_redirect_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconf',
            name='site_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
