# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-09 02:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20171207_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='display_name',
        ),
    ]
