# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0108_auto_20171212_0217'),
        ('core', '0023_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Company'),
        ),
    ]
