# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20171221_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconf',
            name='wx_next_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
