# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-21 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_siteconf_wx_next_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
    ]
