# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-28 03:10
from __future__ import unicode_literals

import core.models.attachment
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20171225_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=core.models.attachment.upload_path),
        ),
    ]
