# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-28 10:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20171228_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='info',
            field=models.TextField(blank=True, verbose_name='其它信息'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='name',
            field=models.CharField(max_length=200, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='title',
            field=models.CharField(max_length=200, verbose_name='公司名称'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
