# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-02 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20180102_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconf',
            name='wx_report_tpl',
        ),
        migrations.AddField(
            model_name='siteconf',
            name='wx_tpl_bind',
            field=models.CharField(blank=True, max_length=200, verbose_name='微信绑定通知模板ID'),
        ),
        migrations.AddField(
            model_name='siteconf',
            name='wx_tpl_report',
            field=models.TextField(blank=True, max_length=200, verbose_name='微信报表通知模板ID'),
        ),
    ]
