# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-02 15:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20180102_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconf',
            old_name='wx_tpl_bind',
            new_name='wx_tpl_verify',
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_token', to=settings.AUTH_USER_MODEL),
        ),
    ]
