# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-02 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20180102_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconf',
            name='wx_tpl_report',
            field=models.CharField(blank=True, max_length=200, verbose_name='微信报表通知模板ID'),
        ),
    ]
