# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('domain', models.CharField(blank=True, max_length=255, verbose_name='域名')),
            ],
        ),
    ]
