# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 05:07
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_auto_20170817_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preference',
            field=jsonfield.fields.JSONField(blank=True, default={}, verbose_name='偏好设置'),
        ),
    ]
