# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_profile_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='手机'),
        ),
    ]
