# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_auto_20171121_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, verbose_name='头像'),
        ),
    ]
