# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_auto_20171205_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.SmallIntegerField(choices=[(1, '男性'), (2, '女性')], default=1),
        ),
    ]
