# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-31 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=1, verbose_name='编号')),
                ('date', models.DateField(verbose_name='时间')),
            ],
        ),
        migrations.AddField(
            model_name='entitylist',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='归还单编号'),
        ),
    ]
