# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-14 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0003_auto_20180414_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revertlist',
            options={'verbose_name': '归还单', 'verbose_name_plural': '归还单'},
        ),
    ]
