# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 19:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='企业名称')),
                ('type', models.CharField(choices=[('limited', '有限责任公司'), ('stock', '股份有限公司'), ('partnership', '合伙企业(有限合伙)'), ('collective', '集体所有制(股份合作)'), ('sole', '个人独资企业')], default='limited', max_length=20, verbose_name='公司类型')),
                ('registered_capital', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='注册资金')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='地址')),
                ('uscc', models.CharField(blank=True, max_length=255, verbose_name='社会统一信用代码号')),
                ('registered_at', models.DateField(blank=True, verbose_name='注册日期')),
                ('expired_at', models.DateField(blank=True, verbose_name='执照有效日期')),
                ('business_license', models.CharField(blank=True, max_length=255, verbose_name='营业执照号')),
                ('industry', models.CharField(choices=[('auto_parts', '汽配'), ('food', '餐饮'), ('clother', '服装'), ('ad', '广告'), ('property', '房地产'), ('service', '服务业'), ('trade', '贸易'), ('entertainment', '娱乐')], default='auto_parts', max_length=50, verbose_name='所属行业')),
                ('national_tax_id', models.CharField(blank=True, max_length=255, verbose_name='国税登记证')),
                ('national_tax_sn', models.CharField(blank=True, max_length=255, verbose_name='国税编码')),
                ('national_tax_staff', models.CharField(blank=True, max_length=255, verbose_name='国税专管员')),
                ('national_tax_branch', models.CharField(blank=True, choices=[('baiyun', '白云区'), ('tianhe', '天河区'), ('panyu', '番禺区'), ('yuexiu', '越秀区'), ('haizhu', '海珠区'), ('zengcheng', '增城区'), ('huadu', '花都区'), ('other', '其它地区')], max_length=10, verbose_name='国税所属分局')),
                ('national_tax_phone', models.CharField(blank=True, max_length=255, verbose_name='国税电话')),
                ('local_tax_id', models.CharField(blank=True, max_length=255, verbose_name='地税登记证')),
                ('local_tax_sn', models.CharField(blank=True, max_length=255, verbose_name='地税编码')),
                ('local_tax_staff', models.CharField(blank=True, max_length=255, verbose_name='地税专管员')),
                ('local_tax_branch', models.CharField(blank=True, choices=[('baiyun', '白云区'), ('tianhe', '天河区'), ('panyu', '番禺区'), ('yuexiu', '越秀区'), ('haizhu', '海珠区'), ('zengcheng', '增城区'), ('huadu', '花都区'), ('other', '其它地区')], max_length=10, verbose_name='地税所属分局')),
                ('local_tax_phone', models.CharField(blank=True, max_length=255, verbose_name='地税电话')),
                ('taxpayer_bank', models.CharField(blank=True, max_length=255, verbose_name='纳税开户银行')),
                ('taxpayer_account', models.CharField(blank=True, max_length=255, verbose_name='纳税账号')),
                ('ss_bank', models.CharField(blank=True, help_text='不填，默认为纳税开户行', max_length=255, verbose_name='社保开户银行')),
                ('ss_account', models.CharField(blank=True, help_text='不填，默认为纳税账号', max_length=255, verbose_name='代扣社保账号')),
                ('ss_number', models.CharField(blank=True, max_length=255, verbose_name='单位社保号')),
                ('credit_rating', models.CharField(choices=[('good', '良好'), ('bad', '差'), ('very_bad', '很差')], default='good', max_length=10, verbose_name='信用评级')),
                ('taxpayer_type', models.CharField(choices=[('general', '一般纳税人'), ('small', '小规模纳税人')], default='small', max_length=10, verbose_name='纳税人类型')),
                ('scale_size', models.CharField(choices=[('small', '小型企业 (50人以下)'), ('medium', '中型企业 (50-200人)'), ('large', '大型企业 (200人以上)')], default='small', max_length=10, verbose_name='规模')),
                ('status', models.CharField(choices=[('normal', '正常'), ('closed', '关闭')], default='normal', max_length=10, verbose_name='公司状态')),
                ('website', models.CharField(blank=True, max_length=255, verbose_name='公司网站')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bookkeeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='记账会计')),
                ('salesman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='业务员')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='合同抬头')),
                ('content', models.TextField(blank=True, verbose_name='合同内容')),
                ('type', models.CharField(choices=[('tax', '报税服务')], max_length=10, verbose_name='合同类型')),
                ('subscription_type', models.CharField(choices=[('onetime', '一次性结算'), ('month', '按月结算'), ('season', '按季度结算'), ('year', '按年结算')], max_length=10, verbose_name='结算类型')),
                ('duration', models.PositiveIntegerField(default=3, help_text='选择结算类型，自动按一次性/月/季度/年结算', verbose_name='服务期限')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('expired_at', models.DateField(verbose_name='到期日期')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='合同金额')),
                ('receivables', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='应收款项')),
                ('received', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='已收款项')),
                ('arrearage', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='欠款')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('review', '审核中'), ('approved', '审核通过'), ('perform', '执行中'), ('suspend', '暂停'), ('expired', '到期'), ('halted', '终止')], default='draft', max_length=10, verbose_name='合同状态')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='crm.Company', verbose_name='公司')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL, verbose_name='业务员')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='企业名称')),
                ('sfz', models.CharField(max_length=255, unique=True, verbose_name='身份证')),
                ('gender', models.CharField(choices=[('male', '男性'), ('female', '女性')], default='male', max_length=5, verbose_name='性别')),
                ('birthdate', models.DateField(blank=True, verbose_name='生日')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='电话')),
                ('wechat', models.CharField(blank=True, max_length=100, verbose_name='微信')),
                ('weibo', models.CharField(blank=True, max_length=100, verbose_name='微博')),
                ('qq', models.CharField(blank=True, max_length=100, verbose_name='QQ')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='ShareHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('legal', '法人'), ('share', '股东')], default='share', max_length=10, verbose_name='身份')),
                ('share', models.FloatField(default=0.1, verbose_name='占比')),
                ('people_name', models.CharField(blank=True, editable=False, max_length=200)),
                ('company_title', models.CharField(blank=True, editable=False, max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Company')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.People')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='shareholder',
            unique_together=set([('people', 'company')]),
        ),
    ]
