# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20170723_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='企业名称'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='company_title',
            field=models.CharField(editable=False, max_length=255, verbose_name='公司抬头'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='salesman_name',
            field=models.CharField(editable=False, max_length=100, verbose_name='业务员'),
        ),
    ]
