# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20170723_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='expired_at',
            field=models.DateField(blank=True, null=True, verbose_name='执照有效日期'),
        ),
    ]
