# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20170723_0405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': '公司', 'verbose_name_plural': '公司'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': '合同', 'verbose_name_plural': '合同'},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name': '雇员', 'verbose_name_plural': '雇员'},
        ),
        migrations.AlterModelOptions(
            name='shareholder',
            options={'verbose_name': '股份持有人', 'verbose_name_plural': '股份持有人'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='duration',
            field=models.PositiveIntegerField(default=3, help_text='选择结算类型，自动按一次性/月/季度/年结算', verbose_name='服务期'),
        ),
    ]
