# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20170723_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='has_expired',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('normal', '正常'), ('closed', '关闭'), ('suspend', '暂停'), ('interest', '意向'), ('halted', '终止')], default='normal', help_text='暂停：客户欠费违约暂停服务', max_length=10, verbose_name='公司状态'),
        ),
    ]
