# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20170724_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='has_expired',
            field=models.BooleanField(default=False, editable=False, verbose_name='执照过期'),
        ),
        migrations.AlterField(
            model_name='company',
            name='note',
            field=models.TextField(blank=True, help_text='可添加公司的其它备注信息', verbose_name='备注'),
        ),
    ]
