# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 16:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0008_auto_20170725_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='people',
            name='sfz',
            field=models.CharField(blank=True, max_length=255, verbose_name='身份证'),
        ),
    ]
