# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20170725_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='部门名称')),
                ('company_title', models.CharField(blank=True, editable=False, max_length=200, verbose_name='公司抬头')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Department', verbose_name='父级部门')),
            ],
        ),
    ]
