# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 16:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20170725_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='bookkeeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='crm.People', verbose_name='记账会计'),
        ),
        migrations.AlterField(
            model_name='company',
            name='salesman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='crm.People', verbose_name='业务员'),
        ),
        migrations.AlterField(
            model_name='people',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Department', verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='people',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='登陆用户'),
        ),
    ]
