# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 16:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_remove_people_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='bookkeeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='记账会计'),
        ),
        migrations.AlterField(
            model_name='company',
            name='salesman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='业务员'),
        ),
    ]
