# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_remove_company_has_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='company',
        ),
        migrations.RemoveField(
            model_name='department',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='people',
            name='user',
        ),
        migrations.AlterField(
            model_name='people',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='people',
            name='sfz',
            field=models.CharField(max_length=255, unique=True, verbose_name='身份证'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
