# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_auto_20170725_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='individual_account',
            field=models.CharField(blank=True, max_length=255, verbose_name='基本户开账号'),
        ),
        migrations.AddField(
            model_name='company',
            name='individual_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='基本户开户地址'),
        ),
        migrations.AddField(
            model_name='company',
            name='op_address',
            field=models.CharField(blank=True, help_text='不填，默认为公司注册地址', max_length=255, verbose_name='实际经营地址'),
        ),
        migrations.AddField(
            model_name='company',
            name='ss_date',
            field=models.DateField(blank=True, null=True, verbose_name='社保购买时间'),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='info',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='is_contactor',
            field=models.BooleanField(default=False, verbose_name='主要联系人'),
        ),
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('limited', '有限责任公司'), ('individual', '个体工商户'), ('stock', '股份有限公司'), ('partnership', '合伙企业(有限合伙)'), ('collective', '集体所有制(股份合作)'), ('sole', '个人独资企业')], default='limited', max_length=20, verbose_name='公司类型'),
        ),
    ]
