# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_auto_20170725_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxBureau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, choices=[('baiyun', '白云区'), ('tianhe', '天河区'), ('panyu', '番禺区'), ('yuexiu', '越秀区'), ('haizhu', '海珠区'), ('zengcheng', '增城区'), ('huadu', '花都区'), ('other', '其它地区')], max_length=50, verbose_name='所属区')),
                ('bureau', models.CharField(blank=True, choices=[('national', '国税局'), ('local', '地税局')], max_length=50, verbose_name='税局')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='地址')),
            ],
            options={
                'verbose_name': '税局',
                'verbose_name_plural': '税局',
            },
        ),
    ]
