# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_taxbureau'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxbureau',
            name='office',
            field=models.CharField(blank=True, max_length=255, verbose_name='分局名称'),
        ),
    ]
