# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_auto_20170725_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='scale_size',
            field=models.CharField(choices=[('small', '小型企业 (50人以内)'), ('medium', '中型企业 (50-200人)'), ('large', '大型企业 (200人以上)')], default='small', max_length=10, verbose_name='规模'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('normal', '正常'), ('abnormal', '经营异常')], default='normal', help_text='经营异常: 已被工商局列入经营异常名录', max_length=10, verbose_name='公司状态'),
        ),
    ]
