# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_auto_20170726_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(choices=[('auto_parts', '汽配'), ('food', '餐饮'), ('clother', '服装'), ('wholesale', '批发业'), ('arch', '建筑'), ('ad', '广告'), ('property', '房地产'), ('service', '服务业'), ('trade', '贸易'), ('entertainment', '娱乐')], default='auto_parts', max_length=50, verbose_name='所属行业'),
        ),
        migrations.AlterField(
            model_name='people',
            name='sfz',
            field=models.CharField(max_length=255, verbose_name='身份证'),
        ),
    ]
