# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_company_has_custom_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='has_customer_files',
            field=models.BooleanField(default=False, verbose_name='是否有存放客户资料'),
        ),
    ]
