# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_company_has_customer_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='has_customer_files',
            field=models.BooleanField(default=False, help_text='详细的资料信息请在备注里添加', verbose_name='是否有存放客户资料'),
        ),
    ]
