# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_auto_20170821_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ic_status',
            field=models.CharField(choices=[('normal', '正常'), ('abnormal', '经营异常')], default='normal', help_text='经营异常: 已被工商局列入经营异常名录', max_length=10, verbose_name='工商状态'),
        ),
        migrations.AlterField(
            model_name='company',
            name='registered_capital',
            field=models.DecimalField(decimal_places=0, help_text='单位 (万元)', max_digits=20, verbose_name='注册资金'),
        ),
    ]
