# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_auto_20170821_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='legal_people',
            field=models.CharField(blank=True, max_length=200, verbose_name='法人'),
        ),
    ]
