# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_auto_20170831_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='registered_capital',
            field=models.DecimalField(decimal_places=2, help_text='单位 (万元)', max_digits=19, verbose_name='注册资金'),
        ),
    ]
