# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 05:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0039_auto_20170831_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='national_tax_sn',
        ),
    ]
