# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0041_auto_20170909_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='credit_rating',
            field=models.CharField(choices=[('良好', '良好'), ('一般', '一般'), ('差', '差'), ('很差', '很差')], default='良好', max_length=10, verbose_name='信用评级'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ic_status',
            field=models.CharField(choices=[('正常', '正常'), ('经营异常', '经营异常')], default='正常', help_text='经营异常: 已被工商局列入经营异常名录', max_length=10, verbose_name='工商状态'),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(choices=[('汽配', '汽配'), ('餐饮', '餐饮'), ('服装', '服装'), ('批发业', '批发业'), ('建筑', '建筑'), ('商贸', '商贸'), ('广告', '广告'), ('房地产', '房地产'), ('服务业', '服务业'), ('贸易', '贸易'), ('娱乐', '娱乐')], default='汽配', max_length=50, verbose_name='所属行业'),
        ),
        migrations.AlterField(
            model_name='company',
            name='scale_size',
            field=models.CharField(choices=[('小型企业', '小型企业'), ('中型企业人)', '中型企业人)'), ('大型企业)', '大型企业)')], default='小型企业', max_length=10, verbose_name='规模'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('有效', '有效'), ('无效', '无效')], default='有效', help_text='无效状态，不再为客户提供服务', max_length=10, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='company',
            name='taxpayer_type',
            field=models.CharField(choices=[('一般纳税人', '一般纳税人'), ('小规模纳税人', '小规模纳税人')], default='小规模纳税人', max_length=10, verbose_name='纳税人类型'),
        ),
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('有限责任公司', '有限责任公司'), ('个体工商户', '个体工商户'), ('股份有限公司', '股份有限公司'), ('合伙企业(有限合伙)', '合伙企业(有限合伙)'), ('集体所有制(股份合作)', '集体所有制(股份合作)'), ('个人独资企业', '个人独资企业')], default='有限责任公司', max_length=20, verbose_name='公司类型'),
        ),
    ]
