# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 18:43
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0042_auto_20170912_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='shareholder_info',
            field=jsonfield.fields.JSONField(blank=True, editable=False, verbose_name='股东信息'),
        ),
    ]
