# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0043_company_shareholder_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholder',
            name='role',
            field=models.CharField(choices=[('法人', '法人'), ('股东', '股东')], default='股东', max_length=10, verbose_name='身份'),
        ),
    ]
