# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 19:44
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0047_auto_20170912_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='shareholder_info',
            field=jsonfield.fields.JSONField(default='[]', verbose_name='股东信息'),
        ),
    ]
