# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0049_auto_20170912_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ic_status',
            field=models.CharField(choices=[('正常', '正常'), ('经营异常', '经营异常')], default='正常', help_text='经营异常: 已被工商局列入经营异常名录', max_length=10, verbose_name='经营状态'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('有效', '有效'), ('无效', '无效')], default='有效', help_text='无效状态，不再为客户提供服务', max_length=10, verbose_name='代理状态'),
        ),
    ]
