# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 20:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0053_auto_20170912_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemborrowingrecord',
            name='lender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lender', to=settings.AUTH_USER_MODEL, verbose_name='出借者'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item',
            field=models.CharField(blank=True, choices=[('营业执照正本', '营业执照正本'), ('营业执照副本', '营业执照副本'), ('金税盘', '金税盘'), ('发票领购本', '发票领购本'), ('公章', '公章'), ('发票章', '发票章'), ('财务章', '财务章'), ('私章', '私章'), ('公司章程', '公司章程'), ('扣款协议', '扣款协议'), ('开户许可证', '开户许可证'), ('机构信用代码证', '机构信用代码证'), ('身份证原件', '身份证原件'), ('开业通知书', '开业通知书'), ('变更通知书', '变更通知书'), ('账册', '账册'), ('凭证', '凭证'), ('租赁合同', '租赁合同'), ('汇缴报告', '汇缴报告'), ('其它', '其它')], max_length=200, verbose_name='物品'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('寄存', '寄存'), ('借出', '借出'), ('已归还', '已归还'), ('遗失', '遗失')], default='寄存', max_length=200, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='itemborrowingrecord',
            name='borrow_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='借出日期'),
        ),
        migrations.AlterField(
            model_name='itemborrowingrecord',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='借用人'),
        ),
        migrations.AlterField(
            model_name='itemborrowingrecord',
            name='has_returned',
            field=models.BooleanField(default=False, verbose_name='是否已归还'),
        ),
        migrations.AlterField(
            model_name='itemborrowingrecord',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Item', verbose_name='物品'),
        ),
        migrations.AlterField(
            model_name='itemborrowingrecord',
            name='qty',
            field=models.PositiveIntegerField(default=1, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='itemborrowingrecord',
            name='reason',
            field=models.CharField(choices=[('办理业务', '办理业务')], default='办理业务', max_length=200, verbose_name='借出事由'),
        ),
        migrations.AlterField(
            model_name='itemborrowingrecord',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='归还日期'),
        ),
        migrations.AlterField(
            model_name='itemborrowingrecord',
            name='status',
            field=models.CharField(choices=[('借出中', '借出中'), ('已归还', '已归还'), ('遗失', '遗失')], default='借出中', max_length=200, verbose_name='状态'),
        ),
    ]
