# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0060_auto_20170915_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='tax_bureau_password',
            new_name='tax_password',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='tax_bureau_username',
            new_name='tax_username',
        ),
    ]
