# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0061_auto_20170915_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ss_declared',
            field=models.BooleanField(default=False, verbose_name='是否有社保申报'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_declared_begin',
            field=models.DateField(blank=True, null=True, verbose_name='税务申报开始时间'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_disk',
            field=models.CharField(blank=True, choices=[('百望', '百望'), ('航天', '航天')], max_length=100, verbose_name='税控盘'),
        ),
    ]
