# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0063_company_special_taxes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ss_declared',
            field=models.CharField(blank=True, choices=[('有', '有'), ('无', '无')], default='无', max_length=10, verbose_name='是否有社保申报'),
        ),
    ]
