# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0064_auto_20170915_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ss_declared',
            field=models.CharField(blank=True, choices=[('社保', '社保'), ('无', '无')], default='无', max_length=10, verbose_name='社保申报'),
        ),
    ]
