# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 14:52
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('crm', '0066_auto_20170921_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='company',
            name='shareholder_info',
            field=jsonfield.fields.JSONField(default=[], editable=False, verbose_name='股东信息'),
        ),
    ]
