# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 15:03
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0067_auto_20171005_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
