# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0068_auto_20171005_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='bookkeeper_username',
        ),
        migrations.RemoveField(
            model_name='company',
            name='salesman_username',
        ),
    ]
