# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0069_auto_20171007_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='has_expired',
            field=models.BooleanField(default=False, editable=False, verbose_name='过期'),
        ),
    ]
