# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0076_auto_20171007_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholder',
            name='people',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.People', verbose_name='客户'),
        ),
    ]
