# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0077_auto_20171008_0307'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shareholder',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='shareholder',
            name='people',
        ),
    ]
