# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0080_auto_20171011_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='company_title',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
