# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0082_auto_20171012_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='count',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
