# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0083_receipt_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='count',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='received_at',
        ),
        migrations.AddField(
            model_name='receipt',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Company'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='日期'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='type',
            field=models.CharField(choices=[('签收', '签收'), ('归还', '归还')], default='签收', max_length=50, verbose_name='类型'),
        ),
    ]
