# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0084_auto_20171012_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='items',
            field=models.TextField(blank=True, editable=False, verbose_name='物品列表'),
        ),
    ]
