# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-14 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0086_auto_20171013_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='item',
            name='company',
        ),
        migrations.RemoveField(
            model_name='item',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='log',
            name='item',
        ),
        migrations.RemoveField(
            model_name='log',
            name='user',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='company',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='user',
        ),
        migrations.AlterField(
            model_name='company',
            name='license_status',
            field=models.CharField(blank=True, choices=[('有效', '有效'), ('即将过期', '即将过期'), ('已过期', '已过期'), ('永久有效', '永久有效')], default='有效', max_length=50, verbose_name='执照状态'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
