# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0088_company_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='custom_entry_no',
        ),
        migrations.RemoveField(
            model_name='company',
            name='custom_org_code',
        ),
        migrations.AddField(
            model_name='company',
            name='has_czk',
            field=models.CharField(choices=[('有', '有'), ('无', '无')], default='无', max_length=100, verbose_name='是否有才智卡'),
        ),
        migrations.AlterField(
            model_name='company',
            name='custom_expired_at',
            field=models.DateField(blank=True, null=True, verbose_name='报关有效期'),
        ),
        migrations.AlterField(
            model_name='company',
            name='custom_register_no',
            field=models.CharField(blank=True, max_length=255, verbose_name='海关注册代码'),
        ),
    ]
