# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0094_auto_20171102_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contactor_phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='负责人电话'),
        ),
    ]
