# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0095_auto_20171102_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='added_value_tax',
            field=models.TextField(blank=True, max_length=255, verbose_name='增值税'),
        ),
        migrations.AddField(
            model_name='company',
            name='batch',
            field=models.CharField(choices=[('批量', '批量')], default='', max_length=100, verbose_name='批量'),
        ),
        migrations.AddField(
            model_name='company',
            name='const_tax',
            field=models.CharField(blank=True, max_length=255, verbose_name='定税'),
        ),
        migrations.AddField(
            model_name='company',
            name='declare_info',
            field=models.TextField(blank=True, verbose_name='申报区备注'),
        ),
        migrations.AddField(
            model_name='company',
            name='income_tax',
            field=models.TextField(blank=True, max_length=255, verbose_name='所得税'),
        ),
    ]
