# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0096_auto_20171107_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='added_value_tax',
            field=models.CharField(blank=True, max_length=255, verbose_name='增值税'),
        ),
        migrations.AlterField(
            model_name='company',
            name='income_tax',
            field=models.CharField(blank=True, max_length=255, verbose_name='所得税'),
        ),
    ]
