# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0097_auto_20171107_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='batch',
            field=models.CharField(blank=True, choices=[('批量', '批量')], default='', max_length=100, verbose_name='批量'),
        ),
    ]
