# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0098_auto_20171107_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cut_tax',
            field=models.CharField(blank=True, max_length=255, verbose_name='减税'),
        ),
        migrations.AddField(
            model_name='company',
            name='withhold_invoice',
            field=models.CharField(blank=True, max_length=255, verbose_name='代扣发票'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_disk',
            field=models.CharField(blank=True, choices=[('百望', '百望'), ('百望*', '百望*'), ('航天', '航天'), ('航天*', '航天*'), ('*', '*')], help_text='带*表示电子发票', max_length=100, verbose_name='税控盘'),
        ),
    ]
