# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0100_auto_20171107_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='withholding',
        ),
        migrations.AddField(
            model_name='company',
            name='invoice',
            field=models.CharField(blank=True, max_length=255, verbose_name='代开发票'),
        ),
    ]
