# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 13:20
from __future__ import unicode_literals

from django.db import migrations, models


def forwards(apps, schema_editor):
    Company = apps.get_model('crm', 'Company')

    for obj in Company.objects.all():
        obj.national_tax_office_new = obj.national_tax_office.full_title if obj.national_tax_office else ''
        obj.local_tax_office_new = obj.local_tax_office.full_title if obj.local_tax_office else ''
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0103_auto_20171203_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='local_tax_office_new',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='national_tax_office_new',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(forwards)

    ]
