# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0105_auto_20171208_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='national_tax_office_new',
            new_name='national_tax_office',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='local_tax_office_new',
            new_name='local_tax_office',
        ),
    ]
