# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0106_auto_20171208_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='local_tax_office',
            field=models.CharField(blank=True, max_length=255, verbose_name='地税局'),
        ),
        migrations.AlterField(
            model_name='company',
            name='national_tax_office',
            field=models.CharField(blank=True, max_length=255, verbose_name='国税局'),
        ),
        migrations.AlterField(
            model_name='company',
            name='registered_capital',
            field=models.DecimalField(decimal_places=2, default=1, help_text='单位 (万元)', max_digits=19, verbose_name='注册资金'),
        ),
    ]
