# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0107_auto_20171209_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='tax_disk',
            field=models.CharField(blank=True, choices=[('无', '无'), ('百望', '百望'), ('百望*', '百望*'), ('航天', '航天'), ('航天*', '航天*'), ('*', '*')], default='无', help_text='带*表示电子发票', max_length=100, verbose_name='税控盘'),
        ),
    ]
