# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-27 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0108_auto_20171212_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='culture_expenses',
            field=models.CharField(blank=True, choices=[('有', '有'), ('无', '无')], max_length=100, verbose_name='文化事业费'),
        ),
        migrations.AddField(
            model_name='company',
            name='individual_tax',
            field=models.CharField(blank=True, choices=[('有', '有'), ('无', '无')], max_length=100, verbose_name='个税'),
        ),
        migrations.AddField(
            model_name='company',
            name='national_tax_type',
            field=models.CharField(blank=True, choices=[('有', '有'), ('无', '无')], max_length=100, verbose_name='国税税种'),
        ),
        migrations.AddField(
            model_name='company',
            name='sale_tax',
            field=models.CharField(blank=True, choices=[('有', '有'), ('无', '无')], max_length=100, verbose_name='消费税'),
        ),
        migrations.AddField(
            model_name='company',
            name='stamp_duty',
            field=models.CharField(blank=True, choices=[('有', '有'), ('无', '无')], max_length=100, verbose_name='印花税'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_disk',
            field=models.CharField(blank=True, choices=[('无', '无'), ('百望', '百望'), ('航天', '航天')], default='无', help_text='带*表示电子发票', max_length=100, verbose_name='税控盘'),
        ),
    ]
