# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-23 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0108_auto_20171212_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('有效', '有效'), ('无效', '无效'), ('歇业', '歇业'), ('筹备', '筹备')], default='有效', help_text='无效状态，不再为客户提供服务', max_length=10, verbose_name='代理状态'),
        ),
    ]
