# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-28 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0109_auto_20180327_2255'),
        ('crm', '0109_auto_20180123_1544'),
    ]

    operations = [
    ]
