# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-28 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0110_merge_20180328_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='electronic_invoicing',
            field=models.CharField(blank=True, choices=[('有', '有'), ('无', '无')], max_length=100, verbose_name='电子发票'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_disk',
            field=models.CharField(blank=True, choices=[('无', '无'), ('百望', '百望'), ('航天', '航天')], default='无', max_length=100, verbose_name='税控盘'),
        ),
    ]
