# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-29 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0111_auto_20180328_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='quota_month',
            field=models.CharField(blank=True, max_length=255, verbose_name='定额(月)'),
        ),
        migrations.AddField(
            model_name='company',
            name='quota_quarter',
            field=models.CharField(blank=True, max_length=255, verbose_name='定额(季)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='electronic_invoicing',
            field=models.CharField(blank=True, choices=[('有', '有'), ('无', '无'), ('手撕发票', '手撕发票')], max_length=100, verbose_name='电子发票'),
        ),
    ]
