# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-20 06:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0113_company_environmental_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='taxpayer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxpayer', to=settings.AUTH_USER_MODEL, verbose_name='报税会计'),
        ),
    ]
