# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-08-01 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0115_auto_20181228_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='tags',
        ),
        migrations.AddField(
            model_name='company',
            name='tag',
            field=models.CharField(blank=True, max_length=100, verbose_name='标签'),
        ),
    ]
