# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-29 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0116_auto_20190802_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='tax_disk',
            field=models.CharField(blank=True, choices=[('无', '无'), ('百望', '百望'), ('航天', '航天'), ('托管(百望)', '托管(百望)'), ('托管(航天)', '托管(航天)')], default='无', max_length=100, verbose_name='税控盘'),
        ),
    ]
