# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-03 16:54
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tag_taggeditem'),
        ('project', '0007_auto_20171204_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags'),
        ),
    ]
