# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_project_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='ext',
            new_name='file_type',
        ),
    ]
