# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20171204_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='ext',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
    ]
