# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_file_ext'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='status',
            field=models.CharField(choices=[('active', '可见'), ('delete', '删除')], default='normal', max_length=50),
        ),
    ]
