# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 07:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0011_auto_20171204_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='feature_doc',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='feature_task',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='last_activity_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='prefs',
            field=jsonfield.fields.JSONField(default={}, verbose_name='偏好设置'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', '活动'), ('inactive', '不再活动'), ('archived', '存档'), ('deleted', '删除')], default='active', max_length=200),
        ),
    ]
