# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20171204_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', '活动'), ('inactive', '不再活动'), ('archive', '存档'), ('delete', '删除')], default='active', max_length=200),
        ),
    ]
