# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 07:53
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20171204_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=django_fsm.FSMField(default='active', max_length=50),
        ),
    ]
