# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 08:17
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20171204_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='state',
            field=django_fsm.FSMField(default='new', max_length=50),
        ),
    ]
