# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 11:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0018_auto_20171204_1927'),
    ]

    operations = [

    ]
