# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_auto_20171204_1927'),
    ]

    operations = [

    ]
