# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_remove_project_memberships'),
    ]

    operations = [

    ]
