# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_auto_20171204_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
    ]
