# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_auto_20171205_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='project',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='who',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
