# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-07 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_auto_20171205_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='colour',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
