# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 13:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0029_category_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='project.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set([('project', 'user')]),
        ),
    ]
