# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 18:17
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_auto_20171208_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-created',), 'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.RemoveField(
            model_name='file',
            name='file_type',
        ),
        migrations.AlterField(
            model_name='file',
            name='privacies',
            field=jsonfield.fields.JSONField(blank=True, default=[]),
        ),
    ]
