# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-21 15:46
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ('-date', 'company'), 'verbose_name': '查账', 'verbose_name_plural': '查账'},
        ),
        migrations.AlterField(
            model_name='result',
            name='data',
            field=jsonfield.fields.JSONField(blank=True, default='{}'),
        ),
    ]
