# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-23 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20171221_2346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Result',
            new_name='Report',
        ),
    ]
