# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-02 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20171224_0115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('-date', 'company'), 'verbose_name': '查报表', 'verbose_name_plural': '查报表'},
        ),
    ]
