# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-02 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20180102_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='has_notified',
            field=models.BooleanField(default=False, editable=False, verbose_name='是否通知过了'),
        ),
    ]
